platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet

inputs:
  - name: service-repo

outputs:
  - name: build-output

run:
  path: sh
  args: ["service-repo/ci/tasks/build.sh"]
