# pipeline for dotnet-core-helloWorld app.

groups:
- name: dotnet-core-hello-world
  jobs:
  - build-service

resources:
- name: service-repo
  type: git
  source:
    uri: https://github.com/miclip/dotnet-core-example.git
    branch: master

- name: dotnet
  type: docker-image
  source:
    repository: miclip/dotnet-resource
    tag: latest

jobs:
- name: build-service
  public: true
  serial: true
  plan:
  - get: service-repo
    trigger: true
  - put: dotnet
    params:
     directory: service-repo
    
  